services:
  postgres:
    image: postgres:18
    container_name: pdvediel-postgres
    environment:
      POSTGRES_DB: pdvediel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/02-data.sql

volumes:
  postgres_data: