spring:
  application:
    name: pdvEdiel
  datasource:
    url: jdbc:postgresql://localhost:5432/pdvediel
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false